name: ycapp_bloc
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  rxdart: ^0.24.0
  firebase_analytics: ^6.0.0
  cloud_firestore: ^0.14.3
  firebase_remote_config: ^0.3.0+3
  firestore_ui: ^1.11.0

  ycapp_messaging:
    path: ../ycapp_messaging

  ycapp_analytics:
    path: ../ycapp_analytics

  ycapp_foundation:
    path: ../ycapp_foundation

  sqflite: ^1.3.0
  flutter_local_notifications: ^1.4.0
  device_info: ^0.4.2+1
  path_provider: ^1.6.5
  auto_size_text: ^2.1.0
  intl: ^0.16.1
  timezone: ^0.5.6
  connectivity: ^2.0.1

  flutter_async_builder: ^0.0.1+1
  reactive_preferences:
    path: ../../reactive_preferences


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.feser.ycappbloc
        pluginClass: YcappblocPlugin
      ios:
        pluginClass: YcappblocPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
